-- +goose Up
CREATE TABLE device_resets(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,occurred_at BIGINT NOT NULL);
CREATE INDEX device_resets_user_time ON device_resets(user_id,occurred_at);
-- +goose Down
DROP TABLE device_resets;
